# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('passwordMd5', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('registerDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用户创建时间')),
                ('lastLoginDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
