# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boynextdoor', '0003_auto_20170925_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwordMd5',
            field=models.CharField(max_length=50),
        ),
    ]
