# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boynextdoor', '0005_auto_20170925_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='inactivatedUser',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('passwordMd5', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('registerDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用户创建时间')),
                ('randomKey', models.CharField(max_length=20)),
            ],
        ),
    ]
